# -*- coding: utf-8 -*-
"""ValidationTestDownsample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Ravi-Raghavan/ESE-5460-Final-Project/blob/master/notebooks/ValidationTestDownsample.ipynb

# Downsample Validation and Test

To further reduce computational overhead during training, we performed additional downsampling of the validation and test splits. Although the initial subsampled splits contained approximately 33,000 examples each, evaluating the model at frequent checkpoints—every 50–100 weight updates—proved to be prohibitively expensive.  

To address this, we **randomly downsampled the validation and test sets to 5,000 samples each**, while ensuring that the original label distributions were preserved. This stratified downsampling allowed for efficient evaluation without distorting class proportions.  

By reducing the size of these splits, we were able to maintain frequent model checkpointing and monitoring of validation performance, while keeping the training loop tractable. This approach balances evaluation efficiency with representativeness during model development.
"""

import pandas as pd
import os

# Data Directory
DATA_DIR = "cleaned_data"

# Original Validation and Test Data
VALIDATION_DATA_FILE = os.path.join(DATA_DIR, "validation.csv")
TEST_DATA_FILE = os.path.join(DATA_DIR, "test.csv")

# Load CSVs
validation_df = pd.read_csv(VALIDATION_DATA_FILE)
test_df = pd.read_csv(TEST_DATA_FILE)

# Select a Stratified Sample of 5000
def stratified_sample(df, label_col="2_way_label", sample_size=5000):
    # If dataset size is <= sample size, no need to subsample
    if len(df) <= sample_size:
        return df

    # Identify Sampling Proportion
    sample_proportion = sample_size / len(df)

    # To ensure stratification, sample the same proportion from each class
    stratified_df = df.groupby(label_col, group_keys=False).apply(
        lambda x: x.sample(frac = sample_proportion, random_state=42)
    )

    # Return stratified dataframe
    return stratified_df

# Perform Stratified Sampling
validation_sampled = stratified_sample(validation_df)
test_sampled = stratified_sample(test_df)

# Save modified CSVs
validation_sampled.to_csv(os.path.join(DATA_DIR, "validation_5k.csv"), index = True)
test_sampled.to_csv(os.path.join(DATA_DIR, "test_5k.csv"), index = True)
print("Stratified sampling complete. Sampled images copied.")