# -*- coding: utf-8 -*-
"""ImageCorruptionAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Ravi-Raghavan/ESE-5460-Final-Project/blob/master/notebooks/ImageCorruptionAnalysis.ipynb

# Image Corruption Identification
"""

from PIL import Image
import os

# Identify Corrupted Images
def identify_corrupted_images(split):
    # Directory of images
    directory = f"{split}_images"

    # Store total count, number of corrupted images, corrupted file names, and corrupted index number from CSV
    count = 0
    corrupted = 0
    corrupted_file_names = []
    corrupted_numbers = []

    # Iterate through all files, store list of corrupted file names
    for filename in os.listdir(directory):
        # Get Image File Path
        path = os.path.join(directory, filename)

        # Increment total count
        count += 1

        # Try to open image
        try:
            img = Image.open(path).convert("RGB") # Try to Fetch RGB Image
            img.verify()   # Verifies integrity without fully decoding
        except Exception:
            # If we encounter an error, we know we have a corrupted image
            corrupted += 1 # Increment corruption count
            corrupted_file_names.append(filename) # Store corrupted file name

            # extract number before ".jpg"
            try:
                num = int(filename.split(".")[0])
                corrupted_numbers.append(num)
            except:
                pass

    # Save corrupted numbers
    num_txt = f"{split}_corrupted_indices.txt"
    with open(num_txt, "w") as f:
        for n in corrupted_numbers:
            f.write(f"{n}\n")

    # Save corrupted filenames
    file_txt = f"{split}_corrupted_filenames.txt"
    with open(file_txt, "w") as f:
        for name in corrupted_file_names:
            f.write(f"{name}\n")

    print(f"Split: {split}, Corrupted: {corrupted}, Total: {count}, %: {100 * corrupted / count}%")

identify_corrupted_images("train")

identify_corrupted_images("validation")

identify_corrupted_images("test")