# -*- coding: utf-8 -*-
"""Milestone #2_Ravi_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLLbIED0UEJaxXDhb4ZpWUhJrB1egUMC

# Analysis of BERT Results: Milestone #2

## Training + Validation Loss
"""

import json
import matplotlib.pyplot as plt

TRAINER_FILE = "Milestone2-Baseline-BERT-FineTuning/trainer_state.json"

# Load trainer state
with open(TRAINER_FILE, "r") as f:
    state = json.load(f)

log_history = state["log_history"]

train_losses = []
eval_losses = []
train_steps = []
eval_steps = []

# Extract losses
for entry in log_history:
    if "loss" in entry:  # training loss
        train_losses.append(entry["loss"])
        train_steps.append(entry["step"])
    if "eval_loss" in entry:  # validation loss
        eval_losses.append(entry["eval_loss"])
        eval_steps.append(entry["step"])

# Plot
plt.figure(figsize=(9, 6))

plt.plot(
    train_steps, train_losses,
    label="Train Loss",
    linewidth=2.2,
    marker="o",
    markersize=4,
    alpha=0.9,
)

plt.plot(
    eval_steps, eval_losses,
    label="Validation Loss",
    linewidth=2.2,
    marker="s",
    markersize=4,
    alpha=0.9,
)

plt.xlabel("Number of Weight Updates", fontsize=13)
plt.ylabel("Loss", fontsize=13)
plt.title("Training vs Validation Loss", fontsize=15, weight="bold")

plt.grid(True, linestyle="--", alpha=0.5)
plt.legend(fontsize=12)
plt.tight_layout()
plt.show()